setup:
    pip install -r requirements.txt
    cp .env.example .env

run:
    @just run-filling
    @just run-loss
    @just run-komponen

run-filling:
    python src/filling.py

run-loss:
    python src/loss.py

run-komponen:
    python src/komponen.py