setup:
    pip install -r requirements.txt
    cp .env.example .env

run:
    @just run-filling
    @just run-loss
    @just run-komponen

run-filling:
    python ./filling.py

run-loss:
    python ./loss.py

run-komponen:
    python ./komponen.py